### ISSUE TITLE
Petsc - segmentation fault

### ISSUE THREAD

**Issue by martinspetlik** [flow123d/flow123d#1468] opened 2022-08-17 13:19 UTC
**Describe the bug**
Segmentation fault error (see attachment) for mesh with fractures. The more fractures, the more often this error occurs.

**To Reproduce**
- run docker image flow123d/flow123d-gnu:3.9.0 with enclosed data
- tested also with  Flow123d, version 3.1.0 commit: 5393e92e3 and no error occurred

[sample.zip](https://github.com/flow123d/flow123d/files/9362978/sample.zip)

![error](https://user-images.githubusercontent.com/23472459/185143756-09f5778f-f500-4c78-b5c3-775f1725a675.png)

**Comment by jbrezmorf** [comment] 2022-08-19 09:04
Most probably duplicate of #1449 and #1469.
The problem appears when using many small regions.

**Comment by Paulie14** [comment] 2022-08-22 13:02
Fixed in issue #1449.
Sample runs fine now.

**Comment by jbrezmorf** [comment] 2022-08-23 13:38
Fixed by #1449

**Closed by jbrezmorf** 2022-08-23 13:38 UTC
Labels: Done, User request
