### ISSUE TITLE
Review transport boundary conditions

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#274] opened 2015-02-06 21:50 UTC
Currently in SoluteTransport_DG we provide these boundary conditions:
- dirichlet
- inflow (prescribed total flux on inlet, zero diffusive flux on outlet)
- neumann (prescribed diffusive flux)
- robin (diffusive flux proportional to concentration difference)

Think if they all are useful and sufficient (e.g. one could prescribe total flux).

"Neumann" is probably not correct name.

**Comment by jbrezmorf** [comment] 2015-03-27 22:43
duplicate of #335

**Comment by jbrezmorf** [comment] 2015-08-25 15:38
Replaced by #414

**Closed by jbrezmorf** 2015-08-25 15:38 UTC
