### ISSUE TITLE
P0_coupling in test 22 fails in PE_intersection

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#611] opened 2016-07-07 08:30 UTC
I wanted to see what happened to test 22, P0_noncompatbile in PE_intersection branch.
It fails due to changes in BIHtree creation in commit d7c79cf129d03154c16bfd56872eaad0a390f200.
But I read the file with solution errors and they all decreased (mainly pressure error in 2D), so I think it is a good fix:) 
On the other hand, I did not investigate what was wrong with BIHtree in this test before.

We should probably look at it before changing reference and merging..

**Comment by jbrezmorf** [comment] 2016-07-07 09:17
There is something rotten there. test 22 fails on windows 32 for unknown
reason. Possibly there was the issue with BIHtree.

**Comment by jbrezmorf** [comment] 2016-08-31 11:04
duplicate of #341

**Closed by jbrezmorf** 2016-08-31 11:04 UTC
Labels: Tests, Todo
