### ISSUE TITLE
Problematic case of DG + Sorption

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#856] opened 2017-05-19 13:43 UTC
Uloha od Jakuba Rihy:
- obdelnik, na spodu puklina s vodivosti 1, sousedni matrice vodivost 1e-13.
- rychlost v matrici vyjde nulova, transport pouze difuzi
- transport v matrici rizeny pouze difuzi vykazuje podivne oscilace, kdy koncentrace na hranicich elementu
  nejsou vubec spojite a pod.
 

TODO:
- v DG transportu, prejmenovat sorpcni koeficient aby byl uzivatel nucen konvertovat jednotky
- vytvořit testovací úlohu pro pouhou difúzi, a další posloupnost úloh přibližujících se problematickému případu

**Comment by jstebel** [comment] 2017-07-12 14:16
Brief description of the test case: Fluid with contaminant is injected into a 2d cylindrical fracture which is on one side connected to a 3d matrix. The amount of contaminant flowing out of the fracture is observed. Due to very low conductivity, the fluid does not flow into matrix, however a small amount of the contaminant is captured in the matrix due to diffusion and sorption.

The test case is problematic because of very low diffusivity in matrix compared to the fracture flow velocity. Consequently, the solution has a very thin layer in the vicinity of the fracture, which requires very fine mesh to capture it accurately. In 2d it is possible to achieve results comparable to reference values (Goldsim). I do not think that the problems indicate any bug in the numerical method.

Further remarks:
- Oscillations are caused by highly anisotropic mesh elements. When dg_penalty is increased from 1 to 1e3 or higher, they disappear. Anyway, it seems that the oscillations do not affect the results of balance (flux through fracture end).
- sorption_mult already renamed to sorption_coefficient in version 2.1

**Comment by jbrezmorf** [comment] 2017-07-18 09:16
- Can we resolve the thin layer by higher order elements?
- Can we set dg_penalty automatically according to mesh anisotropy?

**Comment by jstebel** [comment] 2017-07-24 08:28
> Can we resolve the thin layer by higher order elements?

Indeed, higher order helps (in the committed test case I use dg_order 3) but still is not sufficient.

> Can we set dg_penalty automatically according to mesh anisotropy?

Currently the penalty is 

  dg_penalty * h * f(D),

where h is element diameter and f(D) a function depending on dispersivity tensor on both sides. We could modify it so that instead of h we take e.g.

  h * (h_max/h_min),

where h_max, h_min is the length of the longest and shortest edge, respectively. I will investigate it.

**Comment by jstebel** [comment] 2017-07-24 11:35
I have implemented an automatic increase of dg_penalty for anisotropic mesh elements. It eliminates the oscillations in the present test. However several existing tests do not pass, so their reference files would need to be updated.

**Comment by jbrezmorf** [comment] 2017-07-26 07:53
Differences should not be to big, we should rather check the results before
and after the change in ParaView.

**Comment by jstebel** [comment] 2017-08-02 12:43
Checked and reference files updated. Branch JS_slow_diffusion is ready to merge.

**Closed** 2017-08-11 07:44 UTC
Labels: Done, _day_
