### ISSUE TITLE
memory handling issues

### ISSUE THREAD

**Issue by martinspetlik** [flow123d/flow123d#1469] opened 2022-08-17 13:43 UTC
**Describe the bug**
Some memory issues. 
![invalid pointer](https://user-images.githubusercontent.com/23472459/185147435-f3c37264-5829-4c59-9522-9fd29af37076.png)
![invalid next size](https://user-images.githubusercontent.com/23472459/185147495-7530ec87-0191-4fe8-a8fb-c9e7cf7e9927.png)

**To Reproduce**
- run docker://flow123d/flow123d-gnu:3.9.0 (Digest:sha256:50f42be6f526d3f9f78f16fd28a6470f1ff3dd614acb26ab2fee0c2ad9cd079c) with enclosed data
[samples.zip](https://github.com/flow123d/flow123d/files/9363153/samples.zip)

**Comment by jbrezmorf** [comment] 2022-08-19 09:03
Most probably duplicate of #1449.
The problem appears when using many small regions.

**Comment by martinspetlik** [comment] 2022-08-19 11:20
I am facing the same issue using a reduced number of regions.

![screenshot](https://user-images.githubusercontent.com/23472459/185606760-02bfcb3d-3728-489d-99c2-39bb8f94553f.png)

[failed_sample.zip](https://github.com/flow123d/flow123d/files/9381681/failed_sample.zip)

Tested with docker image flow123d/flow123d-gnu:3.9.0 (id: 49bf6782c6ca)

**Comment by Paulie14** [comment] 2022-08-19 11:27
trying to fix, I will run this sample too.

**Comment by Paulie14** [comment] 2022-08-22 13:04
Fixed in issue https://github.com/flow123d/flow123d/issues/1449.
Sample runs fine now.
Try using the image flow123d:3.9.1 when it is built.

**Comment by martinspetlik** [comment] 2022-08-23 13:10
It seems to work fine. Thanks.

**Comment by jbrezmorf** [comment] 2022-08-23 13:38
Fixed by #1473

**Closed by jbrezmorf** 2022-08-23 13:38 UTC
Labels: Done, User request
