### ISSUE TITLE
Missing values when reading FieldFE from GMSH file

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#1184] opened 2020-02-10 11:50 UTC
**Describe the bug**
When some field is read as !FieldFE from a .msh file, a warning and error message appears that indicates wrong number of elements in the input file (reported by @ales-balvin-tul):
```
00:00:45.549      WARNING.
                  In file '/scratch.ssd/alesbalvin/job_505482.meta-pbs.metacentrum.cz/./dataSevreni/out_b.msh', '$ElementData' section for field 'rozevreni', time: 0.
                  Wrong number of entities: 104380, using 104784 instead.
00:00:45.563 [10] ERROR
                  --------------------------------------------------------
                  User Error: Values of some elements of FieldFE 'rozevreni' is undefined.
                  Please specify in default_value key.

                  At input address: NO_VALUE

                  --------------------------------------------------------
```

**To Reproduce**
- flow123d v. 2.2.1
- link to source files, input files: /auto/liberec3-tul/home/alesbalvin/TACR_PUKLINA/VYPOCTY_MS2/_UCODE_MS2/a2019-10-18_MS2_18x10x/T1_H_JJ_3mm_20ml-5ml_G-B_viceJ

**Comment by jstebel** [comment] 2020-02-10 12:44
Solution for user: add key 'default_value: 0'.
For developers: Flow123d expects value for each element, including boundary elements. The input file apparently contains values only for bulk elements.

**Comment by jbrezmorf** [comment] 2020-02-10 15:38
TODO: Check behavior in the 3.x release. Should be fixed there. It have minor impact on 2.x releases so no plan to backport the fix.

**Comment by jstebel** [comment] 2020-02-11 12:57
Version 3.0.9 has the same behaviour as 2.x - fails due to missing key "default_value".

**Comment by jbrezmorf** [comment] 2020-02-11 14:39
Bug confirmed. If the field is a bulk field only bulk elements should be checked and vice versa.

**Comment by jbrezmorf** [comment] 2020-02-26 22:26
@dflanderka We have to fix the value checking for the FieldFE input.

**Comment by Paulie14** [comment] 2020-05-04 13:13
I studied the problem again under 3.x.x branches and I got similar output:
```
00:00:23.266      MESSAGE.... 104784 bulk elements, 416 boundary elements. 
00:00:25.546      WARNING.In file '/home/paulie/docker_flow123d/2020_06_AB_default_values/./dataSevreni/out_T.msh', '$ElementData' section for field 'transmisivita', time: 0.
                  Wrong number of entities: 104380, using 104784 instead.
00:00:27.202 [0]  ERROR--------------------------------------------------------
                  User Error: Values of some elements of FieldFE 'transmisivita' is undefined.
                  Please specify in default_value key.
```

However, it seems to me that the problem is not due to boundary elements.

The mesh has 104784, with 824 1d elements.  Only 416 of the 1d elements are boundary elements.
Looking at the log, we see
```
- Bulk elementary regions -
                  name                  id dim
                  fracture               3   2
                  region_3               3   1
                  region_4               4   1
```
that there are 2 other 1d regions (the names `region_3` and `region_4` are generated automatically from the region ids in tags in the msh file when reading the corresponding elements).
I do not know, how the input data is generated, however, it apparently does not include the values for the 1d elements in regions `region_3` and `region_4`.
That is why the user gets either the UsrErr, or has to use `default_value`.

**Comment by Paulie14** [comment] 2020-05-04 13:16
Therefore I would pronounce this issue as solved and suggest to close it.

**Closed** 2020-05-05 11:00 UTC
Labels: Done, User request, bug
